project:
  type: website

website:
  title: "Mark Gingrass"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
      - href: booklist.qmd
    right:
      - icon: github
        href: https://github.com/mtgingrass
        aria-label: GitHub
      - icon: youtube
        menu:
          - text: Cradle To Grave R
            href: https://youtube.com/@cradletograver
          - text: Mark Gingras
            href: https://youtube.com/@markgingrass
      - icon: envelope-arrow-up-fill
        href: "mailto:mg@markgingrass.com"  # Ensure correct spacing and quotes
  page-footer: 
    left: "Copyright 2025, Mark Gingrass" 
    right: 
      - icon: github
        href: https://github.com/mtgingrass
      - icon: envelope-arrow-up-fill
        href: "mailto:mg@markgingrass.com"  # Ensure correct spacing and quotes

format:
  html:
    theme: solona
    css: styles.css
    toc: true

editor: visual

freeze: auto

execute:
  freeze: auto