project:
  type: website

website:
  title: "Mark Gingrass"
  site-url: "https://markgingrass.com"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: booklist.qmd

    right:
      - icon: github
        href: https://github.com/mtgingrass
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/markgingrass/
        aria-label: LinkedIn
      - icon: youtube
        href: https://youtube.com/@cradletograver
        aria-label: Cradle To Grave R YouTube
      - icon: youtube
        href: https://youtube.com/@markgingrass
        aria-label: Mark Gingrass YouTube
      - icon: envelope-arrow-up-fill
        href: "mailto:mg@markgingrass.com"
  page-footer: 
    left: "Copyright 2025, Mark Gingrass" 
    right: 
      - icon: github
        href: https://github.com/mtgingrass
      - icon: linkedin
        href: https://www.linkedin.com/in/markgingrass/
      - icon: envelope-arrow-up-fill
        href: "mailto:mg@markgingrass.com"

format:
  html:
    theme: [cosmo, _quarto.scss]
    css: [styles.css]
    toc: true
    code-copy: true
    code-fold: false
    smooth-scroll: true

editor: visual

freeze: auto

execute:
  freeze: auto